# Generated by Django 2.2.5 on 2019-09-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hadread',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
