# Generated by Django 2.2.5 on 2019-09-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_stars_num'),
        ('message', '0003_auto_20190928_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_source_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='消息来源博客ID'),
        ),
    ]
