# Generated by Django 2.2.5 on 2019-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='是否已经发布还是暂存(默认发布)'),
        ),
    ]
