# Generated by Django 2.2.5 on 2019-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='stars_num',
            field=models.IntegerField(default=0, verbose_name='被赞次数'),
        ),
    ]
