# Generated by Django 2.2.5 on 2019-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_star_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.TextField(default='javascript', verbose_name='文章标签（以 / 隔开）'),
        ),
    ]
