# Generated by Django 2.2.5 on 2019-09-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password_encrypeted', models.CharField(max_length=30, verbose_name='被加密后的密码')),
                ('password_salt', models.CharField(max_length=100, verbose_name='对密码加盐时使用的盐')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
