# Generated by Django 2.2.5 on 2019-09-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_encrypeted',
            new_name='password_encrypted',
        ),
    ]
