# Generated by Django 2.2.5 on 2019-09-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190923_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(default='user-avatars/avatar_default.png', height_field=50, upload_to='user-avatars/', verbose_name='头像', width_field=50),
        ),
    ]
