# Generated by Django 2.2.5 on 2019-09-24 03:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190924_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/upload-files/user-avatars/'), upload_to='', verbose_name='头像'),
        ),
    ]
