# Generated by Django 2.2.5 on 2019-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190924_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program_lan',
            field=models.CharField(default='javascript', max_length=100, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_area',
            field=models.CharField(default='前端', max_length=100, verbose_name='语言'),
        ),
    ]
