# Generated by Django 2.2.5 on 2019-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190924_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_encrypted',
            field=models.CharField(max_length=2000, verbose_name='被加密后的密码'),
        ),
    ]
