# Generated by Django 2.2.5 on 2019-09-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190924_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study_area',
        ),
    ]
