# Generated by Django 2.2.5 on 2019-09-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190925_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(upload_to='static/user-upload/user-avatars/', verbose_name='头像'),
        ),
    ]
