# Generated by Django 2.2.5 on 2019-09-30 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0005_auto_20190927_0908'),
        ('user', '0011_auto_20190925_0205'),
        ('blog', '0005_remove_blog_stars_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('star_id', models.AutoField(primary_key=True, serialize=False, verbose_name='赞ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='赞的时间')),
                ('star_for_blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zan_to_blog', to='blog.Blog', verbose_name='赞的被给予方的博客的ID')),
                ('star_for_comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zan_to_blog', to='comment.Comment', verbose_name='赞的被给予方的博客的ID')),
                ('star_from_userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zan_from', to='user.User', verbose_name='赞的发送者ID')),
            ],
        ),
    ]
