# Generated by Django 2.2.5 on 2019-10-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190925_0205'),
        ('star', '0002_auto_20190930_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='star_to_userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_to', to='user.User', verbose_name='赞的接受者ID'),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_from_userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_from', to='user.User', verbose_name='赞的发送者ID'),
        ),
    ]
