# Generated by Django 2.2.5 on 2019-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.IntegerField(default=1, verbose_name='所属博客'),
            preserve_default=False,
        ),
    ]
