# Generated by Django 2.2.5 on 2019-09-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '__first__'),
        ('comment', '0002_comment_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog_title',
            field=models.CharField(default=1, max_length=50, verbose_name='博客标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_blog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='所属博客ID'),
        ),
    ]
