# Generated by Django 2.2.5 on 2019-09-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='评论主ID'),
        ),
    ]
