# Generated by Django 2.2.5 on 2019-09-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
        ('comment', '0005_auto_20190927_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='star.Star', verbose_name='赞id'),
        ),
    ]
